name: Proton-GE WoW64 CI

permissions:
  contents: write

env:
  GH_TOKEN: ${{ github.token }}

on:
  schedule:
    - cron:  '0 0 */3 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Download artifact Bootstrap
        id: download-artifact-boot
        uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          workflow: bootstrap_wow64.yml
          workflow_conclusion: success
          path: /opt
      - uses: actions/checkout@v3
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # when set to "true" but frees about 6 GB
          tool-cache: true
      - name: Build Wine
        run: |
          sudo apt update
          sudo apt install debootstrap perl git wget xz-utils bubblewrap autoconf
          sudo tar -C /opt -xpf "/opt/Bootstraps WoW64/bootstraps_wow64.tar.xz"
          git clone --recurse-submodules http://github.com/gloriouseggroll/proton-ge-custom wine
          cd wine
          cp ../proton-GE-drivepatch.patch ./wine-staging/patches/ntdll-ext4-case-folder/0002-ntdll-server-Mark-drive_c-as-case-insensitive-when-c.patch
          cp ../protonprep-valve-staging.sh ./patches/protonprep-valve-staging.sh
          mkdir ./patches/termux-patches
          cp ../termux-wine-fix-protonge.patch patches/termux-patches
          cp ../pathfix.patch patches/termux-patches
          cp ../ndis_proton.patch patches/termux-patches
          cp ../wine-virtual-memory-proton.patch patches/termux-patches
          cp ../esync-GE.patch patches/termux-patches
          sudo chmod +x -R ./patches/termux-patches
          ls -laR ./patches/
          sleep 30
          ./patches/protonprep-valve-staging.sh
          sed -i 's/tar.gz/tar.xz/' ./Makefile.in
          sed -i -E "$(sed -n '/mv $(REDIST_DIR) $(BUILD_NAME)/=' ./Makefile.in) i\\\tmv \$\(BUILD_NAME\)\/files \$\(BUILD_NAME\)\/wine" ./Makefile.in
          mkdir build && cd build
          ../configure.sh --build-name=wine-action-proton-GE --container-engine=podman
          sudo mkdir -p /data/data/com.termux/files/usr/tmp && sudo chown -R $(whoami):$(whoami) /data/data
          ln -s /tmp/.wine /data/data/com.termux/files/usr/tmp
          sudo chmod -R +x ..
          sudo chown -R $(whoami):$(whoami) ..
          make redist
      - uses: actions/upload-artifact@v4
        with:
          name: PROTON-GE SRC WoW64
          path: ./wine
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: Proton
          files: |
            ./wine/build/wine-action-proton-GE.tar.xz
