name: Wine-GE WoW64 CI

permissions:
  contents: write

env:
  GH_TOKEN: ${{ github.token }}

on:
  schedule:
    - cron:  '0 0 */3 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          workflow: bootstrap_wow64.yml
          workflow_conclusion: success
          path: /opt
      - name: Build Wine
        run: |
          sudo apt update
          sudo apt install debootstrap perl git wget xz-utils bubblewrap autoconf
          sudo tar -C /opt -xpf "/opt/Bootstraps WoW64/bootstraps_wow64.tar.xz"
          git clone --recurse-submodules http://github.com/gloriouseggroll/proton-ge-custom wine
          cd wine
          patch -d wine -Np1 < ../termux-wine-fix.patch
          patch -d wine -Np1 < ../pathfix.patch
          patch -d wine -Np1 < ../ndis_proton.patch
          patch -d wine -Np1 < ../wine-virtual-memory-proton.patch
          patch -d wine -Np1 < ../esync-GE.patch
          ./patches/protonprep-valve-staging.sh
          mkdir build && cd build
          ../configure.sh --build-name=wine-action-proton --container-engine=podman
          make redist
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: Proton
          files: |
            ./wine-action-proton.tar.gz
