name: Proton GE init

permissions:
  contents: write

env:
  GH_TOKEN: ${{ github.token }}

on:
  schedule:
    - cron:  '0 0 */3 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # when set to "true" but frees about 6 GB
          tool-cache: true
      - name: Build Wine
        run: |
          git clone --recurse-submodules http://github.com/gloriouseggroll/proton-ge-custom wine
          cd wine
          ./patches/protonprep-valve-staging.sh
          sed -i '/dlls\/winevulkan\/make_vulkan -x vk.xml/d' ./Makefile.in
          mkdir build && cd build
          ../configure.sh --build-name=wine-action-proton-GE --container-engine=podman
      - uses: actions/upload-artifact@v4
        with:
          name: PROTON-GE SRC WoW64
          path: ./wine