name: Proton-GE WoW64 CI

permissions:
  contents: write

env:
  GH_TOKEN: ${{ github.token }}

on:
  schedule:
    - cron:  '0 0 */3 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Download artifact Bootstrap
        id: download-artifact-boot
        uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          workflow: bootstrap_wow64.yml
          workflow_conclusion: success
          path: /opt
      - uses: actions/checkout@v3
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # when set to "true" but frees about 6 GB
          tool-cache: true
      - name: Build Wine
        run: |
          sudo apt update &>/dev/null
          sudo apt install debootstrap perl git wget xz-utils bubblewrap autoconf automake libtool &>/dev/null
          sudo tar -C /opt -xpf "/opt/Bootstraps WoW64/bootstraps_wow64.tar.xz" &>/dev/null
          git clone --recurse-submodules http://github.com/gloriouseggroll/proton-ge-custom wine &>/dev/null
          cd wine
          cp ../proton-GE-drivepatch.patch ./wine-staging/patches/ntdll-ext4-case-folder/0002-ntdll-server-Mark-drive_c-as-case-insensitive-when-c.patch
          cp ../protonprep-valve-staging.sh ./patches/protonprep-valve-staging.sh
          mkdir ./patches/termux-patches
          cp ../termux-wine-fix-protonge.patch patches/termux-patches
          cp ../pathfix.patch patches/termux-patches
          cp ../ndis_proton.patch patches/termux-patches
          cp ../wine-virtual-memory-proton.patch patches/termux-patches
          cp ../esync-GE.patch patches/termux-patches
          sudo chmod +x -R ./patches/termux-patches
          ./patches/protonprep-valve-staging.sh
          sed -i 's/tar.gz/tar.xz/' ./Makefile.in
          sed -i 's/W_TMP_EARLY=.*/\W_TMP_EARLY="\/data\/data\/com.termux\/files\/usr\/tmp\"/' protonfixes/winetricks
          sed -i -E "$(sed -n '/mv $(REDIST_DIR) $(BUILD_NAME)/=' ./Makefile.in) i\\\tmv \$\(BUILD_NAME\)\/files \$\(BUILD_NAME\)\/wine" ./Makefile.in
          sed -i -E "$(($(sed -n '/ -w/=' default_pfx.py) - 2)) i\    subprocess.run(runtime_args + [\"/bin/bash\", \"-c\",\n        \"mkdir -p /data/data/com.termux/files/usr/tmp/.wine && chmod 700 /data/data/com.termux/files/usr/tmp/.wine\"],\n        env=local_env, check=True)\n" ./default_pfx.py
          sed -i -E "$(sed -n '/$(DOCKER_BASE) $(MAKE) -j$(J)/=' Makefile.in) i\\\techo \"FALLODELREDISTMAKE\"\n\\techo \"$(cat Makefile.in | grep '$(DOCKER_BASE) $(MAKE) -j$(J)')\"\n\\tdf -h" ./Makefile.in
          mkdir build && cd build
          ../configure.sh --build-name=wine-action-proton-GE --container-engine=podman &>/dev/null
          sudo mkdir -p /data/data/com.termux/files/usr/tmp/.wine && sudo chown -R $(whoami):$(whoami) /data/data && sudo chmod 700 /data/data
          sudo chmod -R 777 ..
          sudo chown -R $(whoami):$(whoami) ..
          make V=1 VERBOSE=1 redist
      - uses: actions/upload-artifact@v4
        with:
          name: PROTON-GE SRC WoW64
          path: ./wine
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: Proton
          files: |
            ./wine/build/wine-action-proton-GE.tar.xz
