name: Proton-GE WoW64 CI

permissions:
  contents: write

env:
  GH_TOKEN: ${{ github.token }}

on:
  schedule:
    - cron:  '0 0 */3 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        continue-on-error: true
        with:
          workflow: proton-ge-init.yml
          workflow_conclusion: success
          path: ./
      - name: Build Wine
        run: |
          cd "PROTON-GE SRC WoW64/wine/build"
          make redist
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: Proton
          files: |
            "./PROTON-GE SRC WoW64/wine/build/wine-action-proton-GE.tar.xz"
