name: Wine-GE WoW64 CI

permissions:
  contents: write

env:
  GH_TOKEN: ${{ github.token }}

on:
  schedule:
    - cron:  '0 0 */3 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # when set to "true" but frees about 6 GB
          tool-cache: true
      - name: Build Wine
        run: |
          git clone --recurse-submodules http://github.com/gloriouseggroll/proton-ge-custom wine
          cd wine
          cp ../proton-GE-drivepatch.patch ./wine-staging/patches/ntdll-ext4-case-folder/0002-ntdll-server-Mark-drive_c-as-case-insensitive-when-c.patch
          ./patches/protonprep-valve-staging.sh
          patch -d wine -Np1 < ../termux-wine-fix-protonge.patch
          patch -d wine -Np1 < ../pathfix.patch
          patch -d wine -Np1 < ../ndis_proton.patch
          patch -d wine -Np1 < ../wine-virtual-memory-proton.patch
          patch -d wine -Np1 < ../esync-GE.patch
          sed -i 's/\/files/\/wine/' ./Makefile.in
          sed -i 's/tar.gz/tar.xz/' ./Makefile.in
          sudo mkdir -p /data/data/com.termux/files/usr/tmp/
          sudo chown -R $(whoami):$(whoami) /data/data
          mkdir build && cd build
          ../configure.sh --build-name=wine-action-proton-GE --container-engine=podman
          make redist
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: Proton
          files: |
            ./wine/build/wine-action-proton-GE.tar.xz
