name: Test Release

on:
  schedule:
    - cron:  '0 0 */3 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
      - name: Staging
        run: |
          mkdir -p /data/data/com.termux/files/usr/tmp/
          ln -s /tmp/.wine /data/data/com.termux/files/usr/tmp/.wine
